### ISSUE TITLE
Occasional MDB_BAD_RSLOT error

### ISSUE THREAD

**Issue by scossu** [scossu/lakesuperior#72]
### Environment

Operating system: RHEL 6

Python version: 3.5.1

LAKEsuperior release, branch, or commit #: 1.0.0a16

### Steps to reproduce

Perform a large batch of SPARQL queries on the server. The repository is quite large (~170M triples), however the queries are not very demanding (<1s response time). 

### Observed behavior

Occasionally the following error is raised:

```
2018-05-07 17:33:03,437 ERROR flask.app - Exception on /query/sparql [POST]
Traceback (most recent call last):
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/lakesuperior/endpoints/query.py", line 86, in sparql
    out_stream = query_api.sparql_query(qstr, fmt)
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/lakesuperior/api/query.py", line 128, in sparql_query
    with TxnManager(rdf_store) as txn:
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/lakesuperior/store/ldp_rs/lmdb_store.py", line 62, in __enter__
    self.store.begin(write=self.write)
  File "/data/local/lake/lsup_env/lib64/python3.5/site-packages/lakesuperior/store/ldp_rs/lmdb_store.py", line 341, in begin
    self.data_txn = self.data_env.begin(buffers=True, write=write)
lmdb.BadRslotError: mdb_txn_begin: MDB_BAD_RSLOT: Invalid reuse of reader locktable slot
```

### Expected behavior

No error should be raised.

### Other notes worth mentioning

This exception comes from the LMDB store and seems to be related to thread handling. See https://www.openldap.org/lists/openldap-devel/201409/msg00001.html

**Comment by scossu** [comment]
No longer reproducible.
